theme: jekyll-theme-minimal


title: [Wouter Meijer]
description: | 
  (Bio)Robotics engineer interested in cognition
  
  [linkedin.com/in/wouterjmeijer](linkedin.com/in/wouterjmeijer)
  
  # test

  - a
  - b 
  - c