theme: jekyll-theme-minimal

logo: [img/smile-min.jpg]
title: [Wouter Meijer]
description: | 
  (Bio)Robotics engineer interested in cognition
  (linkedin.com/in/wouterjmeijer)[linkedin.com/in/wouterjmeijer]
  linkedin.com/in/wouterjmeijer